print('Convert Decimal to Binary, Octal and Hexadecimal')
a = int(input('Enter a decimal number to convert '))
b = bin(a)
h = hex(a)
o = oct(a)
print("Decimal Number is ",a)
print("Binary of ",a," is ",b)
print("Octal of ",a," is ",o)
print("Hexadecimal of ",a," is ",h)